#!/bin/sh
# Extract the image name from docker-compose.yaml
image=$(grep 'image:' $(pwd)/docker-compose.yaml | awk '{print $2}')
docker run -i --rm -w "$(pwd)" -v "$(pwd):$(pwd)" "$image" latexindent "$@"
